apiVersion: apps/v1
kind: Deployment
metadata:
  name: makeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makeline-service
  template:
    metadata:
      labels:
        app: makeline-service
    spec:
      containers:
      - name: makeline-service
        image: saizalsaini02/makeline-service:v1
        ports:
        - containerPort: 8080
        env:
        - name: ORDER_DB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URI
        - name: ORDER_DB_NAME
          value: "orders"
        - name: ORDER_DB_COLLECTION_NAME
          value: "orders"
---
apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  selector:
    app: makeline-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
