apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
      - name: store-admin
        image: saizalsaini02/store-admin:v1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
spec:
  type: ClusterIP
  selector:
    app: store-admin
  ports:
    - port: 80
      targetPort: 80
